# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    LaxCorp\CatalogHostingBundle\Helper\RestHelper:
        arguments:
            $apiUrl: '%catalog_hosting.url%'
            $login: '%catalog_hosting.login%'
            $password: '%catalog_hosting.password%'
            $restClient: '@circle.restclient'
            $logger: '@logger'

    LaxCorp\CatalogHostingBundle\Helper\MappingHelper:
        arguments:
            $serializer: '@jms_serializer'

    LaxCorp\CatalogHostingBundle\Helper\CatalogCustomerHelper:


